motd:
  enabled: true

  random: false

  lines:
    - "&aBIGT &7| &fPaper 1.21.10"
    - "&7在线: &b{online}&7/&b{max} &7| &aTPS: &f{tps} &7MSPT: &f{mspt}"

  messages:
    - "&BIGT &7| &f欢迎回来!\\n&7在线: &b{online}&7/&b{max}"
    - "&e生存服 &7| &fPaper 1.21.10\\n&7TPS: &f{tps} &7MSPT: &f{mspt}"

